name: Create Release
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Release Bump
        options: 
        - patch
        - minor
        - major

jobs:
  create-release:
    name: Create a Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push tag
        id: tag_version
        uses: RomainEndelin/github-tag-action@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: '.*' # main, or any vX.Y.Z-beta.N tag
          force_bump: ${{ inputs.bump }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
          prerelease: false
