name: Create Release
on:
  push:
    branches:
      - main
      - public_release
  workflow_dispatch:

jobs:
  create-release:
    name: Create a Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: 'public_release'
          pre_release_branches: 'main'
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
          prerelease: ${{ contains(steps.tag_version.outputs.release_type, 'pre') }}
