name: Simulate Deploy
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  simulate-deploy:
    name: Simulate deploy
    runs-on: ubuntu-latest
    environment: 'staging'
    steps:
      - run: echo "Hello world"
